const A=document.querySelector("#app");
const home=()=>`<section class="hero"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-6"><span class="eyebrow">GESTÃO DO LABORATÓRIO</span><h1 class="display mt-3">Organize o laboratório.<br><span class="green">Sem complicar.</span></h1><p class="lead2 mt-4">Agendamentos, autorizações, limites semanais, horas extras e reportes em uma interface simples para o IFMA.</p><div class="d-flex gap-2 mt-4"><a href="#/estudante" class="btn btn-main">Explorar protótipo <i class="bi bi-arrow-right"></i></a><a href="#regras" class="btn btn-outline-dark rounded-3 px-4 py-3">Orientações</a></div></div><div class="col-lg-6"><div class="visual reveal"><span class="eyebrow">VISÃO DO ESTUDANTE</span><h3 class="fw-bold mt-2">Boa tarde, João.</h3><div class="row g-2 mt-3"><div class="col-6"><div class="metric"><small>HORAS USADAS</small><b class="d-block green">18h</b></div></div><div class="col-6"><div class="metric"><small>DISPONÍVEIS</small><b class="d-block">7h</b></div></div></div><div class="metric mt-3"><small>PRÓXIMO AGENDAMENTO</small><h5 class="fw-bold mt-2">Hoje • 14:00–16:00</h5><p class="mb-0 text-secondary">Laboratório de Informática</p></div></div></div></div></div></section>
<section class="section pt-3"><div class="container"><div class="row"><div class="col-lg-5"><span class="eyebrow">A PROPOSTA</span><h2>Menos improviso.<br>Mais controle.</h2></div><div class="col-lg-7">${[["01","Agenda centralizada","Evita conflitos e mostra os horários livres.","bi-calendar3"],["02","Acesso autorizado","O responsável aprova o aluno antes da primeira reserva.","bi-person-check"],["03","Limite semanal","O supervisor define o teto de horas por aluno.","bi-hourglass-split"],["04","Reportes","Situações irregulares ficam registradas para análise.","bi-flag"]].map(x=>`<div class="feature reveal"><small class="green fw-bold">${x[0]}</small><div><h4 class="fw-bold m-0">${x[1]}</h4><p>${x[2]}</p></div><i class="bi ${x[3]}"></i></div>`).join("")}</div></div></div></section>
<section class="section" id="regras"><div class="container"><span class="eyebrow">REGRAS E ORIENTAÇÕES</span><h2 class="mb-4">Antes de usar o laboratório</h2><div id="carousel" class="carousel slide rules reveal" data-bs-touch="true"><div class="carousel-indicators"><button data-bs-target="#carousel" data-bs-slide-to="0" class="active"></button><button data-bs-target="#carousel" data-bs-slide-to="1"></button><button data-bs-target="#carousel" data-bs-slide-to="2"></button><button data-bs-target="#carousel" data-bs-slide-to="3"></button></div><div class="carousel-inner">
${[["active","01 • AGENDAMENTO","Reserve antes de utilizar.","Consulte a agenda e confirme seu horário. Reservas conflitantes são bloqueadas."],["","02 • AUTORIZAÇÃO","Use somente com autorização.","Seu cadastro precisa ser aprovado pelo responsável ou supervisor."],["","03 • IRREGULARIDADE","Encontrou o laboratório ocupado?","Registre um reporte com horário, turma ou pessoas informadas para análise."],["","04 • HORAS EXTRAS","Precisa passar do limite?","Solicite uma exceção semanal com justificativa. Seu limite permanente não muda."]].map(x=>`<div class="carousel-item ${x[0]}"><div class="rule"><small class="eyebrow text-white-50">${x[1]}</small><h3 class="mt-3">${x[2]}</h3><p>${x[3]}</p></div></div>`).join("")}</div><button class="carousel-control-prev" data-bs-target="#carousel" data-bs-slide="prev"><span class="carousel-control-prev-icon"></span></button><button class="carousel-control-next" data-bs-target="#carousel" data-bs-slide="next"><span class="carousel-control-next-icon"></span></button></div></div></section>
<section class="section"><div class="container"><span class="eyebrow">ROTAS SIMULADAS</span><h2 class="mb-5">Veja cada perfil</h2>${[["estudante","Estudante","Agenda, horas, solicitações e reportes."],["coordenador","Coordenador","Aprovação de alunos e horas extras."],["admin","Supervisor","Limites, ocorrências, usuários e logs."]].map(x=>`<a class="role reveal" href="#/${x[0]}"><b>${x[1]}</b><span>${x[2]}</span><i class="bi bi-arrow-up-right fs-3"></i></a>`).join("")}</div></section>`;

const shell=(title,nav,body)=>`<div class="shell"><aside class="side"><h5>${title}</h5>${nav.map((x,i)=>`<a href="javascript:void(0)"><i class="bi ${x[1]}"></i>${x[0]}</a>`).join("")}<a href="#/" class="mt-4"><i class="bi bi-arrow-left"></i>Voltar</a></aside><section class="dash">${body}</section></div>`;
const stats=(a)=>`<div class="stats reveal">${a.map(x=>`<div class="stat"><b class="${x[2]||""}">${x[0]}</b><small>${x[1]}</small></div>`).join("")}</div>`;
const schedule=(time,name,sub,badge)=>`<div class="schedule"><b>${time}</b><span class="line"></span><div><b>${name}</b><small class="d-block text-secondary">${sub}</small></div><span class="badge-soft">${badge}</span></div>`;

const estudante=()=>shell("🎓 Área do estudante",[["Visão geral","bi-grid"],["Agenda","bi-calendar3"],["Horas","bi-hourglass"],["Reportes","bi-flag"],["Perfil","bi-person"]],`<span class="eyebrow">ESTUDANTE</span><h1>Boa tarde, João.</h1><div class="mt-4">${stats([["18h","AGENDADAS"],["7h","DISPONÍVEIS","green"],["2","RESERVAS ATIVAS"],["0","REPORTES"]])}</div><div class="row g-3 mt-1"><div class="col-xl-7"><div class="panel reveal"><div class="d-flex justify-content-between"><h5>Próximos agendamentos</h5><button class="btn btn-main btn-sm sim">+ Novo</button></div>${schedule("14:00","Laboratório de Informática","Hoje • Projeto de pesquisa","Confirmado")}${schedule("09:00","Laboratório de Informática","Sexta • Atividade orientada","Confirmado")}</div></div><div class="col-xl-5"><div class="panel reveal"><h5>Limite semanal</h5><div class="d-flex justify-content-between mt-4"><span>18h usadas</span><b>25h</b></div><div class="progress mt-2"><div class="progress-bar" style="width:72%"></div></div><p class="text-secondary small mt-3">Restam 7 horas nesta semana.</p><button class="btn btn-outline-success w-100 sim">Solicitar horas extras</button></div></div></div><div class="panel mt-3 reveal"><h5>Ações rápidas</h5><div class="row g-2 mt-2">${[["bi-calendar-plus","Agendar laboratório"],["bi-flag","Reportar problema"],["bi-calendar3","Ver agenda"]].map(x=>`<div class="col-md-4"><div class="action sim"><i class="bi ${x[0]}"></i><b>${x[1]}</b></div></div>`).join("")}</div></div>`);

const coordenador=()=>shell("👨‍🏫 Coordenador",[["Visão geral","bi-grid"],["Meus alunos","bi-people"],["Aprovações","bi-person-check"],["Horas extras","bi-clock-history"],["Agenda","bi-calendar3"]],`<span class="eyebrow">COORDENADOR / RESPONSÁVEL</span><h1>Painel de aprovações</h1><div class="mt-4">${stats([["4","ALUNOS VINCULADOS"],["2","CADASTROS PENDENTES","green"],["1","PEDIDO DE HORAS"],["3","RESERVAS HOJE"]])}</div><div class="row g-3 mt-1"><div class="col-xl-7"><div class="panel reveal"><h5>Solicitações de acesso</h5><div class="table-responsive"><table class="table mt-3"><tbody><tr><td><b>Ana Beatriz</b><small class="d-block text-secondary">Computação • 2026012345</small></td><td class="text-end"><button class="btn btn-success btn-sm sim">Aprovar</button> <button class="btn btn-light btn-sm sim">Recusar</button></td></tr><tr><td><b>Lucas Lima</b><small class="d-block text-secondary">Engenharia • 2026012388</small></td><td class="text-end"><button class="btn btn-success btn-sm sim">Aprovar</button> <button class="btn btn-light btn-sm sim">Recusar</button></td></tr></tbody></table></div></div></div><div class="col-xl-5"><div class="panel reveal"><h5>Horas extras</h5><p class="text-secondary">Marina solicitou uma exceção.</p><div class="p-3 rounded-4" style="background:var(--mint)"><small class="eyebrow">SOLICITADO</small><h2 class="fw-bold green">+5h</h2><small>Conclusão de atividade do projeto.</small></div><div class="d-flex gap-2 mt-3"><button class="btn btn-success flex-fill sim">Aprovar</button><button class="btn btn-light flex-fill sim">Ajustar</button></div></div></div></div><div class="panel mt-3 reveal"><h5>Agenda de hoje</h5>${schedule("10:00","Ana Beatriz","Projeto orientado","12h/25h")}${schedule("14:00","João Silva","Pesquisa","18h/25h")}</div>`);

const admin=()=>shell("🛡️ Supervisão",[["Visão geral","bi-grid"],["Agenda","bi-calendar3"],["Usuários","bi-people"],["Aprovações","bi-person-check"],["Ocorrências","bi-flag"],["Limites","bi-sliders"],["Logs","bi-journal-text"]],`<span class="eyebrow">SUPERVISOR / ADMINISTRADOR</span><h1>Visão geral do laboratório</h1><div class="mt-4">${stats([["6","AGENDAMENTOS"],["2","OCORRÊNCIAS","text-danger"],["3","CADASTROS PENDENTES"],["25h","LIMITE PADRÃO","green"]])}</div><div class="row g-3 mt-1"><div class="col-xl-7"><div class="panel reveal"><h5>Ocorrências recentes</h5><div class="table-responsive"><table class="table mt-3"><tbody><tr><td><b>#291 • Laboratório ocupado</b><small class="d-block text-secondary">João • 14:07</small></td><td><span class="badge-soft">Pendente</span></td></tr><tr><td><b>#290 • Uso sem agendamento</b><small class="d-block text-secondary">Marina • 11:32</small></td><td><span class="badge-soft">Em análise</span></td></tr></tbody></table></div></div></div><div class="col-xl-5"><div class="panel reveal"><h5>Limite semanal padrão</h5><div class="d-flex align-items-end gap-2 mt-3"><h2 id="lim" class="fw-bold green mb-0">25h</h2><span class="text-secondary">por aluno</span></div><input id="range" class="form-range mt-4" type="range" min="5" max="40" value="25"><button class="btn btn-main w-100 mt-3 sim">Salvar configuração</button></div></div></div><div class="panel mt-3 reveal"><h5>Atividade do sistema</h5>${[["15:42","Ocorrência #291 movida para Em análise"],["15:18","Coordenador aprovou +5h para Marina"],["14:07","João registrou ocorrência #291"],["13:50","Novo agendamento criado por Ana"]].map(x=>`<div class="d-flex gap-3 py-2 border-bottom"><small class="text-secondary">${x[0]}</small><span>${x[1]}</span></div>`).join("")}</div>`);

function render(){let r=location.hash.slice(1)||"/";A.innerHTML=r==="/estudante"?(window.studentApp?window.studentApp():estudante()):r==="/coordenador"?coordenador():r==="/admin"?admin():home();scrollTo(0,0);bind();animate()}
function bind(){document.querySelectorAll(".sim").forEach(x=>x.onclick=()=>bootstrap.Toast.getOrCreateInstance(document.querySelector("#toast")).show());let r=document.querySelector("#range");if(r)r.oninput=()=>document.querySelector("#lim").textContent=r.value+"h";if(location.hash==="#/estudante"&&window.bindStudent)window.bindStudent()}
function animate(){if(!window.gsap)return;gsap.registerPlugin(ScrollTrigger);gsap.from("h1,.display",{y:20,opacity:0,duration:.55});gsap.utils.toArray(".reveal").forEach(e=>gsap.fromTo(e,{y:20,opacity:0},{y:0,opacity:1,duration:.55,scrollTrigger:{trigger:e,start:"top 93%"}}))}
addEventListener("hashchange",render);render();
