(function(){
const USERS_KEY="labagenda_auth_users_v1",SESSION_KEY="labagenda_auth_session_v1";
const seed=[
 {id:"stu-joao",name:"João Silva",registration:"2026012345",email:"joao.silva@ifma.edu.br",phone:"(98) 99999-1234",course:"Ciência da Computação",role:"STUDENT",status:"APPROVED",advisor:"Carlos Mendes",hours:18,password:"Lab@123"},
 {id:"stu-ana",name:"Ana Beatriz",registration:"2026012361",email:"ana.beatriz@ifma.edu.br",phone:"(98) 99999-2361",course:"Ciência da Computação",role:"STUDENT",status:"APPROVED",advisor:"Carlos Mendes",hours:12,password:"Lab@123"},
 {id:"stu-lucas",name:"Lucas Lima",registration:"2026012388",email:"lucas.lima@ifma.edu.br",course:"Engenharia",role:"STUDENT",status:"PENDING",advisor:"Carlos Mendes",hours:0,password:"Lab@123",requestedAt:"28/09/2026 09:42"},
 {id:"stu-marina",name:"Marina Costa",registration:"2025011092",email:"marina.costa@ifma.edu.br",course:"Sistemas de Informação",role:"STUDENT",status:"APPROVED",advisor:"Renata Alves",hours:23,password:"Lab@123"},
 {id:"stu-pedro",name:"Pedro Rocha",registration:"2024010433",email:"pedro.rocha@ifma.edu.br",course:"Engenharia",role:"STUDENT",status:"PENDING",advisor:"Renata Alves",hours:0,password:"Lab@123",requestedAt:"27/09/2026 15:10"},
 {id:"stu-camila",name:"Camila Sousa",registration:"2026012410",email:"camila.sousa@ifma.edu.br",course:"Ciência da Computação",role:"STUDENT",status:"PENDING",advisor:"Carlos Mendes",hours:0,password:"Lab@123",requestedAt:"27/09/2026 16:18"},
 {id:"coord-carlos",name:"Carlos Mendes",registration:"COORD-014",email:"carlos.mendes@ifma.edu.br",phone:"(98) 99998-7711",department:"Departamento de Computação",course:"Computação",role:"COORDINATOR",status:"APPROVED",password:"Lab@123"},
 {id:"coord-renata",name:"Renata Alves",registration:"COORD-008",email:"renata.alves@ifma.edu.br",department:"Sistemas de Informação",course:"Sistemas de Informação",role:"COORDINATOR",status:"APPROVED",password:"Lab@123"},
 {id:"coord-paulo",name:"Paulo Nunes",registration:"COORD-021",department:"Engenharia",course:"Engenharia",role:"COORDINATOR",status:"PENDING",password:"Lab@123",requestedAt:"26/09/2026 10:25"},
 {id:"sup-fernanda",name:"Fernanda Oliveira",registration:"SUP-001",email:"fernanda.oliveira@ifma.edu.br",phone:"(98) 99991-4500",department:"Administração do laboratório",course:"Administração do laboratório",role:"SUPERVISOR",status:"APPROVED",password:"Lab@123"},
 {id:"sup-rafael",name:"Rafael Santos",registration:"SUP-002",course:"Suporte técnico",role:"SUPERVISOR",status:"APPROVED",password:"Lab@123"}
];
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let users=read(USERS_KEY,null);if(!users){users=seed;write(USERS_KEY,users)}
let view="login",registerRole="STUDENT";
const labels={APPROVED:"Aprovado",PENDING:"Em análise",REJECTED:"Recusado"},routes={STUDENT:"#/estudante",COORDINATOR:"#/coordenador",SUPERVISOR:"#/admin"};
const save=()=>write(USERS_KEY,users),current=()=>{const id=read(SESSION_KEY,null);return users.find(u=>u.id===id)||null};
window.Auth={
 getUsers(role){return users.filter(u=>!role||u.role===role)},find(reg){return users.find(u=>u.registration.toLowerCase()===String(reg).trim().toLowerCase())},current,
 approvedCoordinators(){return users.filter(u=>u.role==="COORDINATOR"&&u.status==="APPROVED")},
 canAccess(path){const u=current(),expected=path==="/estudante"?"STUDENT":path==="/coordenador"?"COORDINATOR":path==="/admin"?"SUPERVISOR":null;return !!u&&u.status==="APPROVED"&&u.role===expected},
 setStatus(reg,status,reason=""){const u=this.find(reg);if(!u)return false;u.status=status;u.rejectionReason=status==="REJECTED"?(reason||"Cadastro recusado durante a análise."):"";save();return true},
 render(){return `<section class="auth-page"><div class="auth-wrap"><aside class="auth-aside"><div><div class="auth-mark">◇ <b>LabAgenda</b></div><h2 class="fw-bold mt-5">Seu acesso ao laboratório começa aqui.</h2><p>Entre, acompanhe seu cadastro ou solicite acesso ao sistema.</p><div class="auth-features"><div class="auth-feature"><i class="bi bi-shield-check"></i>Acesso condicionado à aprovação</div><div class="auth-feature"><i class="bi bi-calendar-check"></i>Agenda compartilhada e organizada</div><div class="auth-feature"><i class="bi bi-clock-history"></i>Controle de horas e solicitações</div></div></div><small class="text-white-50">IFMA · Laboratório de Informática</small></aside><div class="auth-card"><div class="auth-switch"><button data-auth-view="login" class="${view==="login"?"active":""}">Entrar</button><button data-auth-view="register" class="${view==="register"?"active":""}">Criar cadastro</button><button data-auth-view="status" class="${view==="status"?"active":""}">Consultar situação</button></div>${this.loginView()}${this.registerView()}${this.statusView()}</div></div></section>`},
 loginView(){return `<div class="auth-view ${view==="login"?"active":""}" data-view="login"><span class="eyebrow">BEM-VINDO</span><h3 class="fw-bold mt-2">Acesse sua conta</h3><p class="text-secondary small">Use sua matrícula institucional e senha.</p><form id="loginForm"><label class="form-label">MATRÍCULA</label><input class="form-control" name="registration" autocomplete="username" required><label class="form-label mt-3">SENHA</label><input class="form-control" name="password" type="password" autocomplete="current-password" required><button class="btn btn-main w-100 mt-4">Entrar <i class="bi bi-arrow-right"></i></button><div id="loginMessage"></div></form></div>`},
 registerView(){const coords=this.approvedCoordinators();return `<div class="auth-view ${view==="register"?"active":""}" data-view="register"><span class="eyebrow">NOVO CADASTRO</span><h3 class="fw-bold mt-2">Solicitar acesso</h3><div class="auth-type my-3"><button type="button" data-register-role="STUDENT" class="${registerRole==="STUDENT"?"active":""}"><i class="bi bi-mortarboard"></i><b>Aluno</b><small class="d-block text-secondary">Aprovação do responsável</small></button><button type="button" data-register-role="COORDINATOR" class="${registerRole==="COORDINATOR"?"active":""}"><i class="bi bi-person-workspace"></i><b>Coordenador</b><small class="d-block text-secondary">Aprovação da supervisão</small></button></div><form id="registerForm"><input type="hidden" name="role" value="${registerRole}"><label class="form-label">NOME COMPLETO</label><input class="form-control" name="name" required><div class="row g-2 mt-1"><div class="col-md-6"><label class="form-label">MATRÍCULA</label><input class="form-control" name="registration" required></div><div class="col-md-6"><label class="form-label">E-MAIL INSTITUCIONAL</label><input class="form-control" name="email" type="email" required></div></div>${registerRole==="STUDENT"?`<div class="row g-2 mt-1"><div class="col-md-6"><label class="form-label">CURSO</label><input class="form-control" name="course" required></div><div class="col-md-6"><label class="form-label">TELEFONE</label><input class="form-control" name="phone"></div></div><label class="form-label mt-3">RESPONSÁVEL / COORDENADOR</label><select class="form-select" name="advisor" required><option value="">Selecione um coordenador aprovado</option>${coords.map(c=>`<option value="${c.name}">${c.name} — ${c.department}</option>`).join("")}</select>`:`<label class="form-label mt-3">DEPARTAMENTO</label><input class="form-control" name="department" required>`}<div class="row g-2 mt-1"><div class="col-md-6"><label class="form-label">SENHA</label><input class="form-control" name="password" type="password" minlength="6" required></div><div class="col-md-6"><label class="form-label">CONFIRMAR SENHA</label><input class="form-control" name="confirm" type="password" minlength="6" required></div></div><button class="btn btn-main w-100 mt-4">Enviar cadastro</button><div id="registerMessage"></div></form></div>`},
 statusView(){return `<div class="auth-view ${view==="status"?"active":""}" data-view="status"><span class="eyebrow">ACOMPANHAMENTO</span><h3 class="fw-bold mt-2">Consultar situação</h3><p class="text-secondary small">Esta consulta não realiza login nem concede acesso.</p><form id="statusForm"><label class="form-label">MATRÍCULA</label><div class="d-flex gap-2"><input class="form-control" name="registration" required><button class="btn btn-main">Consultar</button></div><div id="statusResult"></div></form></div>`},
 bind(){document.querySelectorAll("[data-auth-view]").forEach(b=>b.onclick=()=>{view=b.dataset.authView;render()});document.querySelectorAll("[data-register-role]").forEach(b=>b.onclick=()=>{registerRole=b.dataset.registerRole;render()});document.querySelector("#loginForm")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target),u=this.find(f.get("registration")),box=document.querySelector("#loginMessage");if(!u||u.password!==f.get("password")){box.innerHTML='<div class="auth-message error">Matrícula ou senha incorreta.</div>';return}if(u.status==="PENDING"){box.innerHTML='<div class="auth-message warning">Seu cadastro ainda está em análise.</div>';return}if(u.status==="REJECTED"){box.innerHTML=`<div class="auth-message error">Seu cadastro foi recusado.${u.rejectionReason?`<br><small>${u.rejectionReason}</small>`:""}</div>`;return}write(SESSION_KEY,u.id);location.hash=routes[u.role];location.reload()});document.querySelector("#registerForm")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target),box=document.querySelector("#registerMessage");if(f.get("password")!==f.get("confirm")){box.innerHTML='<div class="auth-message error">As senhas não coincidem.</div>';return}if(this.find(f.get("registration"))){box.innerHTML='<div class="auth-message error">Esta matrícula já possui cadastro.</div>';return}const role=f.get("role"),u={id:`${role.toLowerCase()}-${Date.now()}`,name:f.get("name").trim(),registration:f.get("registration").trim(),email:f.get("email").trim(),phone:f.get("phone")||"",course:f.get("course")||f.get("department"),department:f.get("department")||"",advisor:f.get("advisor")||"",hours:0,role,status:"PENDING",password:f.get("password"),requestedAt:new Date().toLocaleString("pt-BR")};users.push(u);save();e.target.reset();box.innerHTML=`<div class="auth-message success">Cadastro realizado com sucesso. Seu cadastro foi enviado para aprovação${role==="COORDINATOR"?" da supervisão":""}.</div>`});document.querySelector("#statusForm")?.addEventListener("submit",e=>{e.preventDefault();const u=this.find(new FormData(e.target).get("registration")),box=document.querySelector("#statusResult");if(!u){box.innerHTML='<div class="auth-message error">Cadastro não encontrado.</div>';return}const cls=u.status==="APPROVED"?"success":u.status==="PENDING"?"warning":"error";box.innerHTML=`<div class="auth-status-result"><div class="d-flex justify-content-between gap-2"><div><h6>${u.name}</h6><small class="text-secondary">${u.registration} · ${u.role==="STUDENT"?"Aluno":"Coordenador"}</small></div><span class="status ${u.status==="APPROVED"?"done":u.status==="PENDING"?"analysis":"denied"}">${labels[u.status]}</span></div>${u.status==="REJECTED"&&u.rejectionReason?`<p class="small text-danger mt-3 mb-0">${u.rejectionReason}</p>`:""}</div>`})},
 syncNav(){const nav=document.querySelector("#nav .navbar-nav");if(!nav)return;const u=current();nav.querySelectorAll('a[href="#/estudante"],a[href="#/coordenador"],a[href="#/admin"]').forEach(a=>{const allowed=u&&(a.hash===routes[u.role]);a.classList.toggle("d-none",!allowed)});let logout=nav.querySelector(".logout-link");if(u&&!logout){nav.insertAdjacentHTML("beforeend",`<a class="nav-link logout-link" href="#/"><i class="bi bi-box-arrow-right"></i> Sair</a>`);logout=nav.querySelector(".logout-link");logout.onclick=e=>{e.preventDefault();localStorage.removeItem(SESSION_KEY);location.hash="/";location.reload()}}else if(!u&&logout)logout.remove()}
};
})();
