const coordinatorUser=Auth.current()?.role==="COORDINATOR"?Auth.current():Auth.find("COORD-014");
const activeCoordinator=coordinatorUser.name;
const directory=Auth.getUsers("STUDENT").map(u=>({id:u.id,name:u.name,registration:u.registration,course:u.course,authorized:u.status==="APPROVED",status:u.status,advisor:u.advisor,mine:u.advisor===activeCoordinator,hours:u.hours||0}));
window.accessLookupHtml=()=>`<div class="panel access-lookup"><div class="d-flex align-items-center gap-3"><div class="icon-box"><i class="bi bi-person-check"></i></div><div><h5 class="mb-0">Consultar permissão de acesso</h5><small class="text-secondary">Pesquise antes de registrar um reporte.</small></div></div><div class="access-search mt-3"><input class="form-control access-query" placeholder="Nome ou matrícula do estudante" aria-label="Pesquisar estudante"><button class="btn btn-main access-button"><i class="bi bi-search"></i> Pesquisar</button></div><div class="lookup-results"></div></div>`;
window.bindAccessLookup=()=>document.querySelectorAll(".access-lookup").forEach(box=>{const input=box.querySelector(".access-query"),results=box.querySelector(".lookup-results");const search=()=>{const q=input.value.trim().toLocaleLowerCase("pt-BR");if(q.length<2){results.innerHTML=`<small class="text-danger">Digite pelo menos 2 caracteres.</small>`;return}const found=directory.filter(p=>p.name.toLocaleLowerCase("pt-BR").includes(q)||p.registration.includes(q));results.innerHTML=found.length?found.map(p=>`<div class="lookup-person"><div class="person-dot">${p.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div><b>${p.name}</b><small class="d-block text-secondary">${p.registration} · ${p.course}</small></div><span class="status ${p.authorized?"done":"denied"}">${p.authorized?"Acesso autorizado":"Sem permissão"}</span></div>`).join(""):`<div class="empty-state py-3">Nenhum estudante encontrado.</div>`};box.querySelector(".access-button").onclick=search;input.onkeydown=e=>{if(e.key==="Enter")search()}});
window.injectAdminLookup=()=>{const dash=document.querySelector(".dash");if(!dash||dash.querySelector(".access-lookup"))return;const h1=dash.querySelector("h1");h1.insertAdjacentHTML("afterend",window.accessLookupHtml())};

const coordStore={get(k,f){try{return JSON.parse(localStorage.getItem(`labagenda_coord_${k}`))??f}catch{return f}},set(k,v){localStorage.setItem(`labagenda_coord_${k}`,JSON.stringify(v))}};
const pendingSeed=directory.filter(p=>p.mine&&p.status==="PENDING").map((p,i)=>({id:11+i,name:p.name,registration:p.registration,course:p.course,requested:Auth.find(p.registration)?.requestedAt||"Recentemente"}));
const extraSeed=[{id:21,name:"João Silva",registration:"2026012345",hours:5,reason:"Conclusão do projeto integrador",date:"22/09/2026"},{id:22,name:"Ana Beatriz",registration:"2026012361",hours:2,reason:"Preparação para apresentação",date:"27/09/2026"}];
let coordState={view:"overview",pending:pendingSeed,extras:coordStore.get("extras",extraSeed),month:new Date(new Date().getFullYear(),new Date().getMonth(),1),selected:new Date(),bookings:coordStore.get("bookings",[
  {id:31,date:iso(new Date()),start:"08:00",end:"10:00",title:"Reserva para aula prática",owner:"Carlos Mendes",institutional:true,role:"COORDENAÇÃO",status:"Confirmado"},
  {id:32,date:iso(new Date()),start:"10:00",end:"12:00",title:"Manutenção preventiva",owner:"Fernanda Oliveira",institutional:true,role:"SUPERVISOR",status:"Confirmado"},
  {id:33,date:iso(new Date()),start:"14:00",end:"16:00",title:"Projeto de pesquisa",owner:"João Silva",institutional:false,status:"Confirmado"}
])};
const coordViews=[["overview","Visão geral","bi-grid"],["students","Meus alunos","bi-people"],["approvals","Aprovações","bi-person-check"],["extras","Horas extras","bi-clock-history"],["agenda","Agendamento","bi-calendar3"],["occurrences","Ocorrências","bi-flag"],["profile","Perfil","bi-person"]];
function coordNotificationCount(view){if(view==="approvals")return coordState.pending.length;if(view==="extras")return coordState.extras.length;if(view==="occurrences"){const mine=directory.filter(x=>x.mine).map(x=>x.name);return (window.labOccurrences||[]).filter(x=>mine.includes(x.author)&&x.status!=="Resolvida").length}return 0}
function coordNav(){return `<aside class="side student-side"><h5>👨‍🏫 Coordenador</h5>${coordViews.map(x=>{const count=coordNotificationCount(x[0]);return `<a href="#" class="coord-nav ${coordState.view===x[0]?"active":""}" data-view="${x[0]}"><i class="bi ${x[2]}"></i>${x[1]}${count?`<span class="count-pill">${count}</span>`:""}</a>`}).join("")}<a href="#/" class="mt-4"><i class="bi bi-arrow-left"></i>Voltar</a></aside>`}
function coordMobile(){return `<nav class="mobile-student-nav">${coordViews.map(x=>{const count=coordNotificationCount(x[0]);return `<button class="coord-nav ${coordState.view===x[0]?"active":""}" data-view="${x[0]}">${x[1]}${count?`<span class="count-pill">${count}</span>`:""}</button>`}).join("")}</nav>`}
function coordHead(k,t,d,a=""){return `<div class="view-head"><div><span class="eyebrow">${k}</span><h1>${t}</h1><p>${d}</p></div>${a}</div>`}
function coordOverview(){return `<section>${coordHead("COORDENADOR","Boa tarde, professor Carlos.","Gerencie seus alunos e as solicitações pendentes.")}${accessLookupHtml()}${stats([[directory.filter(x=>x.mine).length,"MEUS ALUNOS"],[coordState.pending.length,"CADASTROS PENDENTES","text-danger"],[coordState.extras.length,"PEDIDOS DE HORAS"],[coordState.bookings.filter(x=>x.date===iso(new Date())).length,"RESERVAS HOJE"]])}<div class="row g-3 mt-1"><div class="col-lg-7"><div class="panel"><h5>Pendências recentes</h5>${[...coordState.pending.slice(0,2).map(x=>({name:x.name,detail:"Solicitação de cadastro",view:"approvals"})),...coordState.extras.slice(0,1).map(x=>({name:x.name,detail:`Solicitou +${x.hours} horas`,view:"extras"}))].map(x=>`<div class="request-row"><div class="person-dot">${x.name.split(" ").map(y=>y[0]).join("").slice(0,2)}</div><div class="flex-grow-1"><b>${x.name}</b><small class="d-block text-secondary">${x.detail}</small></div><button class="btn btn-sm btn-light coord-go" data-view="${x.view}">Analisar</button></div>`).join("")||`<div class="empty-state">Tudo em dia.</div>`}</div></div><div class="col-lg-5"><div class="panel"><h5>Ações rápidas</h5>${[["students","bi-people","Ver meus alunos"],["agenda","bi-calendar-plus","Criar agendamento"],["profile","bi-person","Editar perfil"]].map(x=>`<div class="action coord-go mt-2" data-view="${x[0]}"><i class="bi ${x[1]}"></i><b>${x[2]}</b></div>`).join("")}</div></div></div></section>`}
function studentsView(){const mine=directory.filter(x=>x.mine);return `<section>${coordHead("MEUS ALUNOS","Alunos vinculados","Consulte o acesso e o uso de horas dos estudantes sob sua orientação.")}<div class="panel"><div class="access-search mb-3"><input id="studentFilter" class="form-control" placeholder="Filtrar por nome ou matrícula"><button class="btn btn-light"><i class="bi bi-search"></i></button></div><div class="table-responsive"><table class="table student-table"><thead><tr><th>Aluno</th><th>Horas nesta semana</th><th>Situação</th></tr></thead><tbody id="studentRows">${mine.map(studentRow).join("")}</tbody></table></div></div></section>`}
function studentRow(p){const label=p.status==="APPROVED"?"Autorizado":p.status==="REJECTED"?"Recusado":"Aguardando aprovação";return `<tr data-search="${(p.name+p.registration).toLowerCase()}"><td><b>${p.name}</b><small class="d-block text-secondary">${p.registration} · ${p.course}</small></td><td><b>${p.hours}h</b><small class="d-block text-secondary">de 25h</small></td><td><span class="status ${p.status==="APPROVED"?"done":p.status==="PENDING"?"analysis":"denied"}">${label}</span></td></tr>`}
function approvalsView(){return `<section>${coordHead("APROVAÇÕES","Solicitações de cadastro","Apenas solicitações de estudantes vinculados a você.")}<div class="panel"><h5>${coordState.pending.length} solicitações pendentes</h5><div class="mt-3">${coordState.pending.length?coordState.pending.map(p=>`<div class="approval-card"><div class="d-flex align-items-center gap-3"><div class="person-dot">${p.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div class="flex-grow-1"><b>${p.name}</b><small class="d-block text-secondary">${p.registration} · ${p.course}</small><small class="text-secondary">Solicitado ${p.requested}</small></div><div class="approval-actions"><button class="btn btn-success btn-sm decide-approval" data-id="${p.id}" data-action="approved"><i class="bi bi-check-lg"></i> Aprovar</button><button class="btn btn-light btn-sm decide-approval" data-id="${p.id}" data-action="denied">Recusar</button></div></div></div>`).join(""):`<div class="empty-state"><i class="bi bi-check-circle fs-2 d-block mb-2"></i>Nenhuma solicitação pendente.</div>`}</div></div></section>`}
function extrasView(){return `<section>${coordHead("HORAS EXTRAS","Solicitações de horas","Analise pedidos feitos somente pelos seus alunos.")}<div class="panel"><h5>${coordState.extras.length} pedidos aguardando análise</h5><div class="mt-3">${coordState.extras.length?coordState.extras.map(p=>`<div class="approval-card"><div class="d-flex align-items-center gap-3"><div class="icon-box"><i class="bi bi-clock-history"></i></div><div class="flex-grow-1"><b>${p.name} · +${p.hours}h</b><small class="d-block text-secondary">${p.registration} · ${p.date}</small><p class="small mb-0 mt-2">${p.reason}</p></div><div class="approval-actions"><button class="btn btn-success btn-sm decide-extra" data-id="${p.id}" data-action="approved">Aprovar</button><button class="btn btn-light btn-sm decide-extra" data-id="${p.id}" data-action="denied">Recusar</button></div></div></div>`).join(""):`<div class="empty-state"><i class="bi bi-check-circle fs-2 d-block mb-2"></i>Nenhum pedido pendente.</div>`}</div></div></section>`}
function coordBookingItem(b){const mine=b.owner===activeCoordinator;return `<div class="booking-card ${b.institutional?"institutional":"student-booking"} ${mine?"is-mine":""}"><div class="d-flex justify-content-between gap-2"><b>${b.title}</b><div class="booking-labels">${mine?'<span class="mine-tag">Você</span>':""}${b.institutional?`<span class="institutional-tag">${b.role||"COORDENAÇÃO"}</span>`:`<span class="badge-soft">ALUNO</span>`}</div></div><small class="text-secondary">${b.owner}</small><div class="meta"><span><i class="bi bi-calendar3"></i> ${brDate(b.date)}</span><span><i class="bi bi-clock"></i> ${b.start}–${b.end}</span></div></div>`}
function coordCalendar(){const m=coordState.month,y=m.getFullYear(),mo=m.getMonth(),start=new Date(y,mo,1-new Date(y,mo,1).getDay());let cells="";for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=iso(d),bs=coordState.bookings.filter(b=>b.date===key);cells+=`<button class="cal-day coord-day ${d.getMonth()!==mo?"muted":""} ${key===iso(coordState.selected)?"selected":""}" data-date="${key}"><span class="day-num">${d.getDate()}</span><div>${bs.map(b=>`<span class="cal-dot ${b.institutional?"institutional-dot":"student-dot"} ${b.owner===activeCoordinator?"mine-dot":""}"></span>`).join("")}</div><small>${bs.length?`${bs.length} reserva${bs.length>1?"s":""}`:""}</small></button>`}return `<div class="calendar-toolbar"><button class="btn btn-light coord-prev"><i class="bi bi-chevron-left"></i></button><h5>${m.toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</h5><button class="btn btn-light coord-next"><i class="bi bi-chevron-right"></i></button></div><div class="calendar-grid">${["DOM","SEG","TER","QUA","QUI","SEX","SÁB"].map(x=>`<span class="weekday">${x}</span>`).join("")}${cells}</div>`}
function agendaCoordView(){const date=iso(coordState.selected),items=coordState.bookings.filter(x=>x.date===date);return `<section>${coordHead("AGENDAMENTO","Agenda do laboratório","Verde identifica alunos, vermelho indica reservas institucionais e azul destaca as suas.",`<button class="btn btn-main" data-bs-toggle="modal" data-bs-target="#coordBookingModal"><i class="bi bi-plus-lg"></i> Agendar horário</button>`)}<div class="calendar-wrap"><div class="panel">${coordCalendar()}</div><div class="panel"><span class="eyebrow">${brDate(date)}</span><h5 class="mt-2">Agendamentos do dia</h5><div class="mt-3">${items.length?items.map(coordBookingItem).join(""):`<div class="empty-state">Nenhuma reserva neste dia.</div>`}</div><div class="agenda-legend"><span><i class="cal-dot student-dot"></i> Aluno</span><span><i class="cal-dot institutional-dot"></i> Institucional</span><span><i class="cal-dot institutional-dot mine-dot"></i> Você</span></div></div></div>${coordBookingModal()}</section>`}
function coordBookingModal(){return `<div class="modal fade booking-modal institutional-modal" id="coordBookingModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content border-0 rounded-4" id="coordBookingForm"><div class="modal-header"><div><span class="eyebrow">RESERVA INSTITUCIONAL</span><h5 class="modal-title">Agendar laboratório</h5><small class="text-secondary">A reserva será identificada como Coordenação</small></div><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="booking-step"><span>1</span><b>Escolha o dia</b></div>${bookingDatePicker("coordinator",iso(coordState.selected),coordState.bookings)}<div class="booking-step mt-4"><span>2</span><b>Defina o horário</b></div><div class="time-fields"><div class="row g-2"><div class="col-6"><label class="form-label">INÍCIO</label><input class="form-control" name="start" type="time" value="08:00" required></div><div class="col-6"><label class="form-label">TÉRMINO</label><input class="form-control" name="end" type="time" value="10:00" required></div></div></div><div class="booking-step mt-4"><span>3</span><b>Informe a finalidade</b></div><input class="form-control" name="title" placeholder="Ex.: Aula prática" required><div id="coordBookingError" class="text-danger small mt-2"></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-main"><i class="bi bi-check-lg"></i> Confirmar reserva</button></div></form></div></div>`}
function coordProfile(){const p=coordStore.get("profile",{name:"Carlos Mendes",email:"carlos.mendes@ifma.edu.br",department:"Departamento de Computação",phone:"(98) 99998-7711"});return `<section>${coordHead("PERFIL","Meu perfil","Atualize seus dados pessoais e credenciais.")}<div class="row g-3"><div class="col-lg-5"><div class="panel"><div class="profile-summary"><div class="profile-avatar">CM</div><div><h5 class="mb-1">${p.name}</h5><small class="text-secondary">Coordenador · ${p.department}</small></div></div><div class="mt-3"><span class="status done">Conta ativa</span><p class="small text-secondary mt-3 mb-0">Responsável por ${directory.filter(x=>x.mine).length} estudantes.</p></div></div></div><div class="col-lg-7"><div class="panel"><h5>Dados pessoais</h5><form id="coordProfileForm" class="mt-3"><label class="form-label">NOME COMPLETO</label><input class="form-control" name="name" value="${p.name}" required><label class="form-label mt-3">E-MAIL INSTITUCIONAL</label><input class="form-control" name="email" type="email" value="${p.email}" required><div class="row g-2 mt-1"><div class="col-md-6"><label class="form-label">DEPARTAMENTO</label><input class="form-control" name="department" value="${p.department}" required></div><div class="col-md-6"><label class="form-label">TELEFONE</label><input class="form-control" name="phone" value="${p.phone}"></div></div><button class="btn btn-main mt-3">Salvar alterações</button></form></div><div class="panel mt-3"><h5>Alterar senha</h5><form id="coordPasswordForm"><div class="row g-2 mt-3"><div class="col-md-4"><input class="form-control" name="current" type="password" placeholder="Senha atual" required></div><div class="col-md-4"><input class="form-control" name="password" type="password" minlength="6" placeholder="Nova senha" required></div><div class="col-md-4"><input class="form-control" name="confirm" type="password" minlength="6" placeholder="Confirmar" required></div></div><div id="coordPasswordError" class="text-danger small mt-2"></div><button class="btn btn-outline-danger mt-3">Atualizar senha</button></form></div></div></div></section>`}
function coordOccurrences(){const mineNames=directory.filter(x=>x.mine).map(x=>x.name),items=(window.labOccurrences||[]).filter(x=>mineNames.includes(x.author));return `<section>${coordHead("OCORRÊNCIAS","Ocorrências dos meus alunos","Acompanhe e atualize os reportes feitos por estudantes sob sua orientação.")}<div class="panel"><div class="d-flex justify-content-between align-items-center"><h5>${items.length} ocorrências</h5><select class="form-select w-auto occurrence-filter"><option value="all">Todas</option><option value="Pendente">Pendentes</option><option value="Em análise">Em análise</option><option value="Resolvida">Resolvidas</option></select></div><div class="occurrence-list mt-2">${items.length?items.map(x=>window.occurrenceCard(x,true)).join(""):`<div class="empty-state">Nenhuma ocorrência registrada pelos seus alunos.</div>`}</div></div>${window.occurrenceEditorModal?window.occurrenceEditorModal():""}</section>`}

window.coordinatorApp=()=>{let html=`<div class="shell student-shell coord-red">${coordNav()}<div>${coordMobile()}<main class="dash">${({overview:coordOverview,students:studentsView,approvals:approvalsView,extras:extrasView,agenda:agendaCoordView,occurrences:coordOccurrences,profile:coordProfile}[coordState.view]||coordOverview)()}</main></div></div>`;if(coordinatorUser.registration!=="COORD-014"){html=html.replace("Boa tarde, professor Carlos.",`Boa tarde, professor ${coordinatorUser.name.split(" ")[0]}.`);if(coordState.view==="profile")html=html.replaceAll("Carlos Mendes",coordinatorUser.name).replaceAll("carlos.mendes@ifma.edu.br",coordinatorUser.email||"").replaceAll("Departamento de Computação",coordinatorUser.department||coordinatorUser.course||"")}return html};
function refreshCoord(){A.innerHTML=coordinatorApp();bindCoordinator();bindAccessLookup();scrollTo(0,0)}
window.bindCoordinator=()=>{
 bindBookingDatePickers();
 bindBookingAvailability(document.querySelector("#coordBookingForm"),coordState.bookings);
 document.querySelectorAll(".coord-nav,.coord-go").forEach(x=>x.onclick=e=>{e.preventDefault();coordState.view=x.dataset.view;refreshCoord()});
 const filter=document.querySelector("#studentFilter");if(filter)filter.oninput=()=>document.querySelectorAll("#studentRows tr").forEach(r=>r.hidden=!r.dataset.search.includes(filter.value.toLowerCase()));
 document.querySelectorAll(".decide-approval").forEach(x=>x.onclick=()=>{const p=coordState.pending.find(y=>y.id==x.dataset.id),status=x.dataset.action==="approved"?"APPROVED":"REJECTED";Auth.setStatus(p.registration,status,status==="REJECTED"?"Cadastro recusado pelo coordenador responsável.":"");const user=directory.find(y=>y.registration===p.registration);if(user){user.status=status;user.authorized=status==="APPROVED"}coordState.pending=coordState.pending.filter(y=>y.id!=x.dataset.id);refreshCoord();notify(`${p.name}: cadastro ${x.dataset.action==="approved"?"aprovado":"recusado"}.`)});
 document.querySelectorAll(".decide-extra").forEach(x=>x.onclick=()=>{const p=coordState.extras.find(y=>y.id==x.dataset.id);coordState.extras=coordState.extras.filter(y=>y.id!=x.dataset.id);coordStore.set("extras",coordState.extras);refreshCoord();notify(`${p.name}: pedido de horas ${x.dataset.action==="approved"?"aprovado":"recusado"}.`)});
 document.querySelector(".coord-prev")?.addEventListener("click",()=>{coordState.month=new Date(coordState.month.getFullYear(),coordState.month.getMonth()-1,1);refreshCoord()});document.querySelector(".coord-next")?.addEventListener("click",()=>{coordState.month=new Date(coordState.month.getFullYear(),coordState.month.getMonth()+1,1);refreshCoord()});document.querySelectorAll(".coord-day").forEach(x=>x.onclick=()=>{coordState.selected=new Date(`${x.dataset.date}T12:00:00`);refreshCoord()});
 document.querySelector("#coordBookingForm")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target),date=f.get("date"),start=f.get("start"),end=f.get("end"),conflict=coordState.bookings.some(b=>b.date===date&&start<b.end&&end>b.start);if(end<=start||conflict){document.querySelector("#coordBookingError").textContent=end<=start?"O término deve ser posterior ao início.":"Este horário já está reservado.";return}coordState.bookings.push({id:Date.now(),date,start,end,title:f.get("title"),owner:activeCoordinator,institutional:true,role:"COORDENAÇÃO",status:"Confirmado"});coordStore.set("bookings",coordState.bookings);bootstrap.Modal.getInstance(document.querySelector("#coordBookingModal"))?.hide();refreshCoord();notify("Agendamento institucional criado.")});
 document.querySelector("#coordProfileForm")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target);coordStore.set("profile",Object.fromEntries(f.entries()));refreshCoord();notify("Perfil atualizado.")});document.querySelector("#coordPasswordForm")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target);if(f.get("password")!==f.get("confirm")){document.querySelector("#coordPasswordError").textContent="As senhas não coincidem.";return}e.target.reset();notify("Senha atualizada.")});
 const of=document.querySelector(".occurrence-filter");if(of)of.onchange=()=>document.querySelectorAll(".occurrence-card").forEach(x=>x.hidden=of.value!=="all"&&x.dataset.status!==of.value);
 if(window.bindOccurrenceEditing){const mineNames=directory.filter(x=>x.mine).map(x=>x.name);bindOccurrenceEditing(refreshCoord,x=>mineNames.includes(x.author))}
};
if(["#/coordenador","#/estudante","#/admin"].includes(location.hash))render();
