const studentStore={
  get(key,fallback){try{return JSON.parse(localStorage.getItem(`labagenda_${key}`))??fallback}catch{return fallback}},
  set(key,value){localStorage.setItem(`labagenda_${key}`,JSON.stringify(value))}
};

const seedBookings=[
  {id:1,date:new Date().toISOString().slice(0,10),start:"14:00",end:"16:00",title:"Projeto de pesquisa",owner:"Você",mine:true,status:"Confirmado"},
  {id:2,date:new Date(Date.now()+86400000).toISOString().slice(0,10),start:"09:00",end:"11:00",title:"Monitoria de programação",owner:"Ana Beatriz",mine:false,status:"Confirmado"},
  {id:3,date:new Date(Date.now()+2*86400000).toISOString().slice(0,10),start:"10:00",end:"12:00",title:"Atividade orientada",owner:"Marina Costa",mine:false,status:"Confirmado"},
  {id:4,date:new Date().toISOString().slice(0,10),start:"08:00",end:"10:00",title:"Reserva para aula prática",owner:"Carlos Mendes",mine:false,status:"Confirmado",role:"COORDENAÇÃO"},
  {id:5,date:new Date().toISOString().slice(0,10),start:"10:00",end:"12:00",title:"Manutenção preventiva",owner:"Fernanda Oliveira",mine:false,status:"Confirmado",role:"SUPERVISOR"}
];
let studentState={view:"overview",month:new Date(new Date().getFullYear(),new Date().getMonth(),1),selected:new Date(),bookings:studentStore.get("bookings",seedBookings)};
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const iso=d=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
const brDate=s=>new Date(`${s}T12:00:00`).toLocaleDateString("pt-BR",{day:"2-digit",month:"short",year:"numeric"}).replace(" de "," ");
const notify=message=>{const el=document.querySelector("#toast");el.querySelector(".toast-body").innerHTML=`<i class="bi bi-check-circle-fill text-success me-2"></i>${message}`;bootstrap.Toast.getOrCreateInstance(el).show()};

window.bookingDatePicker=(prefix,value,bookings=[])=>`<div class="date-picker" data-picker="${prefix}" data-month="${value.slice(0,7)}" data-bookings='${JSON.stringify(bookings.map(b=>b.date))}'><input type="hidden" name="date" value="${value}"><div class="date-picker-head"><button type="button" class="dp-prev" aria-label="Mês anterior"><i class="bi bi-chevron-left"></i></button><b class="dp-title"></b><button type="button" class="dp-next" aria-label="Próximo mês"><i class="bi bi-chevron-right"></i></button></div><div class="date-picker-grid"></div><div class="booking-legend"><span>Dia com reservas</span></div><div class="selected-date-summary"><i class="bi bi-calendar2-check"></i><div><small>DATA SELECIONADA</small><b class="dp-summary"></b></div></div></div>`;
window.bindBookingDatePickers=()=>document.querySelectorAll(".date-picker").forEach(picker=>{let month=new Date(`${picker.dataset.month}-01T12:00:00`);const input=picker.querySelector('input[name="date"]'),busy=JSON.parse(picker.dataset.bookings||"[]"),draw=()=>{const y=month.getFullYear(),m=month.getMonth(),start=new Date(y,m,1-new Date(y,m,1).getDay()),today=iso(new Date());picker.querySelector(".dp-title").textContent=month.toLocaleDateString("pt-BR",{month:"long",year:"numeric"});picker.querySelector(".dp-summary").textContent=brDate(input.value);picker.querySelector(".date-picker-grid").innerHTML=["D","S","T","Q","Q","S","S"].map(x=>`<span class="dp-week">${x}</span>`).join("")+Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const key=iso(d),past=key<today;return `<button type="button" class="dp-day ${d.getMonth()!==m?"outside":""} ${key===today?"today":""} ${key===input.value?"selected":""} ${busy.includes(key)?"busy":""}" data-date="${key}" ${past?"disabled":""}>${d.getDate()}</button>`}).join("");picker.querySelectorAll(".dp-day:not(:disabled)").forEach(x=>x.onclick=()=>{input.value=x.dataset.date;input.dispatchEvent(new Event("change",{bubbles:true}));month=new Date(`${x.dataset.date.slice(0,7)}-01T12:00:00`);draw()})};picker.querySelector(".dp-prev").onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);draw()};picker.querySelector(".dp-next").onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);draw()};draw()});
window.bindBookingAvailability=(form,bookings=[])=>{
  if(!form)return;
  const area=form.querySelector(".time-fields"),date=form.querySelector('input[name="date"]'),start=form.querySelector('input[name="start"]'),end=form.querySelector('input[name="end"]');
  if(!area||!date)return;
  let anchor=null,board=area.querySelector(".availability-board");
  start.min="07:00";start.max="21:00";end.min="08:00";end.max="22:00";
  if(!board){board=document.createElement("div");board.className="availability-board";area.prepend(board)}
  const manualFields=start.closest(".row");if(manualFields)manualFields.classList.add("d-none");
  start.required=false;end.required=false;
  form.addEventListener("submit",e=>{if(start.value&&end.value)return;e.preventDefault();e.stopImmediatePropagation();const error=form.querySelector('[id$="BookingError"],#bookingError');if(error)error.textContent="Selecione o primeiro e o último bloco do agendamento."},true);
  const interval=(a,b)=>({lo:Math.min(a,b),hi:Math.max(a,b)+1});
  const hasConflict=(lo,hi,day)=>day.some(b=>`${String(lo).padStart(2,"0")}:00`<b.end&&`${String(hi).padStart(2,"0")}:00`>b.start);
  const preview=(hour,day)=>{if(anchor===null)return;const {lo,hi}=interval(anchor,hour),invalid=hasConflict(lo,hi,day);board.querySelectorAll(".time-slot").forEach(slot=>{slot.classList.remove("preview-valid","preview-invalid");const h=Number(slot.dataset.hour);if(h>=lo&&h<hi)slot.classList.add(invalid?"preview-invalid":"preview-valid")})};
  const draw=(error="")=>{
    const day=bookings.filter(b=>b.date===date.value),toMinutes=v=>{if(!v)return 0;const [h,m]=v.split(":").map(Number);return h*60+m},selectedHours=Math.max(0,(toMinutes(end.value)-toMinutes(start.value))/60);
    const slots=Array.from({length:15},(_,i)=>{const h=i+7,s=`${String(h).padStart(2,"0")}:00`,e=`${String(h+1).padStart(2,"0")}:00`,hit=day.find(b=>s<b.end&&e>b.start),chosen=anchor===null&&!hit&&start.value&&s>=start.value&&e<=end.value;return `<button type="button" class="time-slot ${hit?"occupied":""} ${chosen?"chosen":""} ${anchor===h?"anchor":""}" data-hour="${h}" ${hit?"disabled":""}><span>${String(h).padStart(2,"0")}h–${String(h+1).padStart(2,"0")}h</span><small class="d-block">${hit?"ocupado":"livre"}</small></button>`}).join("");
    board.innerHTML=`<div class="availability-head"><div><b>Selecione um intervalo</b><small class="d-block">Clique no início, visualize a faixa e clique no término.</small></div><small class="operating-hours"><i class="bi bi-clock"></i> 07h às 22h</small></div><div class="slot-grid">${slots}</div><div class="slot-legend"><span><i class="free"></i>Livre</span><span><i class="busy"></i>Ocupado</span></div>${anchor!==null?`<div class="selection-hint"><i class="bi bi-cursor"></i>Início em ${String(anchor).padStart(2,"0")}:00. Passe o mouse e escolha o último bloco.</div>`:selectedHours?`<div class="selection-summary"><i class="bi bi-check-circle-fill"></i><div><b>${selectedHours.toLocaleString("pt-BR")} ${selectedHours===1?"hora selecionada":"horas selecionadas"}</b><small>${start.value} às ${end.value}</small></div></div>`:""}<div class="availability-error">${error}</div>`;
    const grid=board.querySelector(".slot-grid");
    grid.onmouseleave=()=>board.querySelectorAll(".time-slot").forEach(s=>s.classList.remove("preview-valid","preview-invalid"));
    board.querySelectorAll(".time-slot").forEach(x=>x.onmouseenter=()=>preview(Number(x.dataset.hour),day));
    board.querySelectorAll(".time-slot:not(:disabled)").forEach(x=>x.onclick=()=>{const h=Number(x.dataset.hour);if(anchor===null&&x.classList.contains("chosen")){start.value="";end.value="";draw();return}if(anchor===null){anchor=h;start.value="";end.value="";draw();return}if(anchor===h){anchor=null;start.value="";end.value="";draw();return}const {lo,hi}=interval(anchor,h);if(hasConflict(lo,hi,day)){draw("Essa faixa atravessa um horário ocupado. Mova o cursor para uma sequência totalmente livre.");return}start.value=`${String(lo).padStart(2,"0")}:00`;end.value=`${String(hi).padStart(2,"0")}:00`;anchor=null;draw()})
  };
  date.addEventListener("change",()=>{anchor=null;start.value="";end.value="";draw()});
  start.addEventListener("change",()=>{anchor=null;draw()});end.addEventListener("change",()=>{anchor=null;draw()});
  start.value="";end.value="";draw();
};

function studentNav(){return `<aside class="side student-side"><h5>🎓 Área do estudante</h5>${[["overview","Visão geral","bi-grid"],["agenda","Agenda","bi-calendar3"],["hours","Horas","bi-hourglass"],["reports","Reportes","bi-flag"],["profile","Perfil","bi-person"]].map(x=>`<a href="#" class="student-nav ${studentState.view===x[0]?"active":""}" data-view="${x[0]}"><i class="bi ${x[2]}"></i>${x[1]}</a>`).join("")}<a href="#/" class="mt-4"><i class="bi bi-arrow-left"></i>Voltar</a></aside>`}
function mobileNav(){return `<nav class="mobile-student-nav">${[["overview","Início"],["agenda","Agenda"],["hours","Horas"],["reports","Reportes"],["profile","Perfil"]].map(x=>`<button class="student-nav ${studentState.view===x[0]?"active":""}" data-view="${x[0]}">${x[1]}</button>`).join("")}</nav>`}
function viewHead(kicker,title,desc,action=""){return `<div class="view-head"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${desc}</p></div>${action}</div>`}
function bookingItem(b,actions=false){return `<div class="booking-card d-flex gap-3"><div class="person-dot">${b.mine?"JS":esc(b.owner).split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div class="flex-grow-1"><div class="d-flex justify-content-between gap-2"><b>${esc(b.title)}</b><span class="badge-soft">${esc(b.status)}</span></div><small class="text-secondary">${esc(b.owner)} · Laboratório de Informática</small><div class="meta"><span><i class="bi bi-calendar3"></i> ${brDate(b.date)}</span><span><i class="bi bi-clock"></i> ${b.start}–${b.end}</span></div>${actions&&b.mine?`<button class="btn btn-link text-danger p-0 mt-2 small cancel-booking" data-id="${b.id}">Cancelar reserva</button>`:""}</div></div>`}

function overviewView(){const mine=studentState.bookings.filter(x=>x.mine&&x.date>=iso(new Date())).sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start));return `<section class="student-view active">${viewHead("ESTUDANTE","Boa tarde, João.","Aqui está o resumo da sua semana.",`<button class="btn btn-main go-view" data-view="agenda"><i class="bi bi-plus-lg"></i> Novo agendamento</button>`)}${window.accessLookupHtml?window.accessLookupHtml():""}${stats([["18h","AGENDADAS"],["7h","DISPONÍVEIS","green"],[mine.length,"RESERVAS ATIVAS"],[studentStore.get("reports",[]).length,"REPORTES"]])}<div class="row g-3 mt-1"><div class="col-xl-7"><div class="panel"><div class="d-flex justify-content-between align-items-center"><h5>Próximos agendamentos</h5><button class="btn btn-sm btn-light go-view" data-view="agenda">Ver agenda</button></div>${mine.length?mine.slice(0,3).map(b=>bookingItem(b)).join(""):`<div class="empty-state">Você não tem reservas futuras.</div>`}</div></div><div class="col-xl-5"><div class="panel"><h5>Limite semanal</h5><div class="d-flex justify-content-between mt-4"><span>18h usadas</span><b>25h</b></div><div class="progress mt-2"><div class="progress-bar" style="width:72%"></div></div><p class="text-secondary small mt-3">Restam 7 horas nesta semana.</p><button class="btn btn-outline-success w-100 go-view" data-view="hours">Solicitar horas extras</button></div></div></div><div class="panel mt-3"><h5>Ações rápidas</h5><div class="row g-2 mt-2">${[["agenda","bi-calendar-plus","Agendar laboratório"],["reports","bi-flag","Reportar problema"],["hours","bi-hourglass","Consultar minhas horas"]].map(x=>`<div class="col-md-4"><div class="action go-view" data-view="${x[0]}"><i class="bi ${x[1]}"></i><b>${x[2]}</b></div></div>`).join("")}</div></div></section>`}

function calendarHtml(){const m=studentState.month,y=m.getFullYear(),mo=m.getMonth(),first=new Date(y,mo,1),start=new Date(y,mo,1-first.getDay());let cells="";for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=iso(d),dayBookings=studentState.bookings.filter(b=>b.date===key);cells+=`<button class="cal-day ${d.getMonth()!==mo?"muted":""} ${key===iso(new Date())?"today":""} ${key===iso(studentState.selected)?"selected":""}" data-date="${key}"><span class="day-num">${d.getDate()}</span><div>${dayBookings.slice(0,3).map(b=>`<span class="cal-dot ${b.mine?"":"other"}"></span>`).join("")}</div><small>${dayBookings.length?`${dayBookings.length} reserva${dayBookings.length>1?"s":""}`:""}</small></button>`}return `<div class="calendar-toolbar"><button class="btn btn-light month-prev" aria-label="Mês anterior"><i class="bi bi-chevron-left"></i></button><h5>${m.toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</h5><button class="btn btn-light month-next" aria-label="Próximo mês"><i class="bi bi-chevron-right"></i></button></div><div class="calendar-grid">${["DOM","SEG","TER","QUA","QUI","SEX","SÁB"].map(x=>`<span class="weekday">${x}</span>`).join("")}${cells}</div>`}
function agendaView(){const selected=iso(studentState.selected),items=studentState.bookings.filter(b=>b.date===selected).sort((a,b)=>a.start.localeCompare(b.start));return `<section class="student-view active">${viewHead("AGENDA","Agenda do laboratório","Consulte os horários de todos e organize sua próxima reserva.",`<button class="btn btn-main" data-bs-toggle="modal" data-bs-target="#bookingModal"><i class="bi bi-plus-lg"></i> Agendar horário</button>`)}<div class="calendar-wrap"><div class="panel" id="calendarBox">${calendarHtml()}</div><div class="panel"><span class="eyebrow">${brDate(selected)}</span><h5 class="mt-2">Agendamentos do dia</h5><div class="mt-3">${items.length?items.map(b=>bookingItem(b,true)).join(""):`<div class="empty-state"><i class="bi bi-calendar2-check fs-2 d-block mb-2"></i>Nenhum horário reservado.</div>`}</div><div class="d-flex gap-3 small mt-3"><span><i class="cal-dot"></i> Seus horários</span><span><i class="cal-dot other"></i> Outros estudantes</span></div></div></div>${bookingModal()}</section>`}
function bookingModal(){return `<div class="modal fade booking-modal" id="bookingModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content border-0 rounded-4" id="bookingForm"><div class="modal-header"><div><span class="eyebrow">NOVA RESERVA</span><h5 class="modal-title">Agendar laboratório</h5><small class="text-secondary">Escolha uma data e um horário disponível</small></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="booking-step"><span>1</span><b>Escolha o dia</b></div>${bookingDatePicker("student",iso(studentState.selected),studentState.bookings)}<div class="booking-step mt-4"><span>2</span><b>Defina o horário</b></div><div class="time-fields"><div class="row g-2"><div class="col-6"><label class="form-label">INÍCIO</label><input class="form-control" name="start" type="time" value="08:00" required></div><div class="col-6"><label class="form-label">TÉRMINO</label><input class="form-control" name="end" type="time" value="10:00" required></div></div></div><div class="booking-step mt-4"><span>3</span><b>Informe a finalidade</b></div><input class="form-control" name="title" maxlength="80" placeholder="Ex.: Projeto de pesquisa" required><div class="text-danger small mt-2" id="bookingError"></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-main"><i class="bi bi-check-lg"></i> Confirmar reserva</button></div></form></div></div>`}

function hoursView(){const reqs=studentStore.get("hour_requests",[{id:1,hours:5,reason:"Conclusão do projeto integrador",date:"22/09/2026",status:"Em análise"}]);return `<section class="student-view active">${viewHead("HORAS","Minhas horas","Acompanhe seu limite semanal e solicite horas adicionais.")}<div class="row g-3"><div class="col-lg-7"><div class="hours-hero d-flex align-items-center justify-content-between gap-4 flex-wrap"><div><small class="text-white-50 fw-bold">SEMANA ATUAL</small><h2 class="fw-bold mt-2">7 horas disponíveis</h2><p class="text-white-50 mb-0">Seu saldo é renovado toda segunda-feira.</p></div><div class="hours-ring"><div><b>18h</b><small>de 25h</small></div></div></div><div class="panel mt-3"><h5>Histórico de uso</h5>${[["Hoje","2h","Projeto de pesquisa"],["24 set","6h","Atividade orientada"],["22 set","5h","Monitoria"],["20 set","5h","Estudo individual"]].map(x=>`<div class="request-row"><div class="icon-box"><i class="bi bi-clock"></i></div><div class="flex-grow-1"><b>${x[2]}</b><small class="d-block text-secondary">${x[0]}</small></div><b>${x[1]}</b></div>`).join("")}</div></div><div class="col-lg-5"><div class="panel"><h5>Solicitar mais horas</h5><p class="text-secondary small">Explique por que precisa ultrapassar o limite nesta semana.</p><form id="hoursForm"><label class="form-label">QUANTIDADE</label><select class="form-select" name="hours" required><option value="">Selecione</option><option value="2">+2 horas</option><option value="5">+5 horas</option><option value="10">+10 horas</option></select><label class="form-label mt-3">JUSTIFICATIVA</label><textarea class="form-control" name="reason" rows="4" minlength="10" placeholder="Descreva a atividade que será realizada..." required></textarea><button class="btn btn-main w-100 mt-3">Enviar solicitação</button></form></div><div class="panel mt-3"><h5>Minhas solicitações</h5>${reqs.length?reqs.map(r=>`<div class="request-row"><div class="flex-grow-1"><b>+${r.hours} horas</b><small class="d-block text-secondary">${esc(r.reason)} · ${r.date}</small></div><span class="status ${r.status==="Aprovado"?"done":"analysis"}">${r.status}</span></div>`).join(""):`<div class="empty-state">Nenhuma solicitação enviada.</div>`}</div></div></div></section>`}

function reportsView(){const reports=studentStore.get("reports",[]);return `<section class="student-view active">${viewHead("REPORTES","Reportar uma situação","Registre ocorrências, problemas técnicos ou situações que precisam de atenção.")}<div class="row g-3"><div class="col-lg-7"><div class="panel"><h5>Novo reporte</h5><form id="reportForm" class="mt-3"><div class="row g-2"><div class="col-md-6"><label class="form-label">CATEGORIA</label><select class="form-select" name="category" required><option value="">Selecione</option><option>Laboratório ocupado</option><option>Uso sem agendamento</option><option>Problema em equipamento</option><option>Bug no sistema</option><option>Outro</option></select></div><div class="col-md-6"><label class="form-label">DATA E HORA</label><input class="form-control" type="datetime-local" name="when" required></div></div><label class="form-label mt-3">TÍTULO</label><input class="form-control" name="title" maxlength="80" placeholder="Resuma o ocorrido" required><label class="form-label mt-3">DESCRIÇÃO</label><textarea class="form-control" name="description" rows="5" minlength="15" placeholder="Conte o que aconteceu com o máximo de detalhes possível..." required></textarea><button class="btn btn-main mt-3"><i class="bi bi-send me-1"></i> Enviar reporte</button></form></div></div><div class="col-lg-5"><div class="panel"><h5>Meus reportes</h5>${reports.length?reports.map(r=>`<div class="report-row"><div class="icon-box"><i class="bi bi-flag"></i></div><div class="flex-grow-1"><b>#${r.id} · ${esc(r.title)}</b><small class="d-block text-secondary">${esc(r.category)} · ${r.date}</small></div><span class="status pending">Pendente</span></div>`).join(""):`<div class="empty-state"><i class="bi bi-inbox fs-2 d-block mb-2"></i>Você ainda não enviou reportes.</div>`}</div><div class="panel mt-3"><small class="eyebrow">ORIENTAÇÃO</small><p class="small text-secondary mt-2 mb-0">Em caso de risco imediato, procure o responsável pelo laboratório. Este formulário não substitui o atendimento de emergência.</p></div></div></div></section>`}

function profileView(){const p=studentStore.get("profile",{name:"João Silva",email:"joao.silva@ifma.edu.br",registration:"2026012345",course:"Ciência da Computação",phone:"(98) 99999-1234"});return `<section class="student-view active">${viewHead("PERFIL","Meu perfil","Atualize seus dados pessoais e sua senha.")}<div class="row g-3"><div class="col-lg-5"><div class="panel"><div class="profile-summary"><div class="profile-avatar">JS</div><div><h5 class="mb-1">${esc(p.name)}</h5><small class="text-secondary">${esc(p.registration)} · ${esc(p.course)}</small></div></div><div class="mt-3 small"><div class="d-flex justify-content-between py-2"><span class="text-secondary">Status</span><span class="status done">Cadastro aprovado</span></div><div class="d-flex justify-content-between py-2"><span class="text-secondary">Vínculo</span><b>Estudante</b></div><div class="d-flex justify-content-between py-2"><span class="text-secondary">Coordenador</span><b>Prof. Carlos Mendes</b></div></div></div></div><div class="col-lg-7"><div class="panel"><h5>Dados pessoais</h5><form id="profileForm" class="mt-3"><label class="form-label">NOME COMPLETO</label><input class="form-control" name="name" value="${esc(p.name)}" required><div class="row g-2 mt-1"><div class="col-md-6"><label class="form-label">E-MAIL INSTITUCIONAL</label><input class="form-control" type="email" name="email" value="${esc(p.email)}" required></div><div class="col-md-6"><label class="form-label">TELEFONE</label><input class="form-control" name="phone" value="${esc(p.phone)}"></div></div><div class="row g-2 mt-1"><div class="col-md-6"><label class="form-label">MATRÍCULA</label><input class="form-control" value="${esc(p.registration)}" disabled></div><div class="col-md-6"><label class="form-label">CURSO</label><input class="form-control" value="${esc(p.course)}" disabled></div></div><button class="btn btn-main mt-3">Salvar alterações</button></form></div><div class="panel mt-3"><h5>Alterar senha</h5><form id="passwordForm" class="mt-3"><div class="row g-2"><div class="col-md-4"><label class="form-label">SENHA ATUAL</label><input class="form-control" type="password" name="current" required></div><div class="col-md-4"><label class="form-label">NOVA SENHA</label><input class="form-control" type="password" name="password" minlength="6" required></div><div class="col-md-4"><label class="form-label">CONFIRMAR</label><input class="form-control" type="password" name="confirm" minlength="6" required></div></div><div class="text-danger small mt-2" id="passwordError"></div><button class="btn btn-outline-success mt-3">Atualizar senha</button></form></div></div></div></section>`}

window.studentApp=()=>`<div class="shell student-shell">${studentNav()}<div>${mobileNav()}<main class="dash">${({overview:overviewView,agenda:agendaView,hours:hoursView,reports:reportsView,profile:profileView}[studentState.view]||overviewView)()}</main></div></div>`;

function refreshStudent(){A.innerHTML=window.studentApp();bindStudent();if(window.bindAccessLookup)window.bindAccessLookup();scrollTo(0,0)}
window.bindStudent=function(){
  bindBookingDatePickers();
  bindBookingAvailability(document.querySelector("#bookingForm"),studentState.bookings);
  document.querySelectorAll(".student-nav,.go-view").forEach(el=>el.onclick=e=>{e.preventDefault();studentState.view=el.dataset.view;refreshStudent()});
  document.querySelector(".month-prev")?.addEventListener("click",()=>{studentState.month=new Date(studentState.month.getFullYear(),studentState.month.getMonth()-1,1);refreshStudent()});
  document.querySelector(".month-next")?.addEventListener("click",()=>{studentState.month=new Date(studentState.month.getFullYear(),studentState.month.getMonth()+1,1);refreshStudent()});
  document.querySelectorAll(".cal-day").forEach(el=>el.onclick=()=>{studentState.selected=new Date(`${el.dataset.date}T12:00:00`);refreshStudent()});
  document.querySelectorAll(".cancel-booking").forEach(el=>el.onclick=()=>{studentState.bookings=studentState.bookings.filter(b=>b.id!=el.dataset.id);studentStore.set("bookings",studentState.bookings);refreshStudent();notify("Agendamento cancelado.")});
  document.querySelector("#bookingForm")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target),date=f.get("date"),start=f.get("start"),end=f.get("end");const conflict=studentState.bookings.some(b=>b.date===date&&start<b.end&&end>b.start);if(end<=start){document.querySelector("#bookingError").textContent="O horário final deve ser posterior ao inicial.";return}if(conflict){document.querySelector("#bookingError").textContent="Este horário conflita com um agendamento existente.";return}studentState.bookings.push({id:Date.now(),date,start,end,title:f.get("title"),owner:"Você",mine:true,status:"Confirmado"});studentStore.set("bookings",studentState.bookings);bootstrap.Modal.getInstance(document.querySelector("#bookingModal"))?.hide();refreshStudent();notify("Agendamento realizado com sucesso.")});
  document.querySelector("#hoursForm")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target),reqs=studentStore.get("hour_requests",[]);reqs.unshift({id:Date.now(),hours:f.get("hours"),reason:f.get("reason"),date:new Date().toLocaleDateString("pt-BR"),status:"Em análise"});studentStore.set("hour_requests",reqs);refreshStudent();notify("Solicitação de horas enviada.")});
  document.querySelector("#reportForm")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target),reports=studentStore.get("reports",[]);reports.unshift({id:String(Date.now()).slice(-4),title:f.get("title"),category:f.get("category"),description:f.get("description"),date:new Date(f.get("when")).toLocaleDateString("pt-BR")});studentStore.set("reports",reports);refreshStudent();notify("Reporte enviado para análise.")});
  document.querySelector("#profileForm")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target),old=studentStore.get("profile",{registration:"2026012345",course:"Ciência da Computação"});studentStore.set("profile",{...old,name:f.get("name"),email:f.get("email"),phone:f.get("phone")});refreshStudent();notify("Perfil atualizado com sucesso.")});
  document.querySelector("#passwordForm")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target);if(f.get("password")!==f.get("confirm")){document.querySelector("#passwordError").textContent="As novas senhas não coincidem.";return}e.target.reset();notify("Senha atualizada com sucesso.")});
};

if(location.hash==="#/estudante")render();
