const supervisorStore={get(k,f){try{return JSON.parse(localStorage.getItem(`labagenda_super_${k}`))??f}catch{return f}},set(k,v){localStorage.setItem(`labagenda_super_${k}`,JSON.stringify(v))}};
const occurrenceSeed=[
 {id:291,title:"Laboratório ocupado sem reserva",category:"Uso sem agendamento",author:"João Silva",registration:"2026012345",advisor:"Carlos Mendes",date:"28/09/2026 14:07",status:"Pendente",description:"O laboratório estava sendo utilizado por uma turma sem registro na agenda."},
 {id:290,title:"Computador 08 não inicializa",category:"Problema em equipamento",author:"Ana Beatriz",registration:"2026012361",advisor:"Carlos Mendes",date:"27/09/2026 11:32",status:"Em análise",description:"O equipamento liga, mas permanece em uma tela preta."},
 {id:289,title:"Falha ao confirmar agendamento",category:"Bug no sistema",author:"Marina Costa",registration:"2025011092",advisor:"Renata Alves",date:"26/09/2026 16:20",status:"Resolvida",description:"O botão de confirmação não respondia no celular."},
 {id:288,title:"Material deixado nas bancadas",category:"Organização",author:"Prof. Carlos Mendes",registration:"COORD-014",advisor:"—",date:"25/09/2026 18:05",status:"Pendente",description:"Materiais foram deixados no laboratório após a última turma."}
];
const studentOccurrences=studentStore.get("reports",[]).map(r=>({id:r.id,title:r.title,category:r.category,author:"João Silva",registration:"2026012345",advisor:"Carlos Mendes",date:r.date,status:"Pendente",description:r.description}));
const storedOccurrences=supervisorStore.get("occurrences",occurrenceSeed);
window.labOccurrences=[...studentOccurrences.filter(r=>!storedOccurrences.some(o=>String(o.id)===String(r.id))),...storedOccurrences];
window.occurrenceCard=o=>`<div class="occurrence-card" data-status="${o.status}"><div class="d-flex justify-content-between gap-3"><div><b>#${o.id} · ${o.title}</b><div class="occ-meta mt-1"><span><i class="bi bi-person"></i> ${o.author}</span><span>${o.registration}</span><span><i class="bi bi-person-badge"></i> ${o.advisor}</span><span><i class="bi bi-clock"></i> ${o.date}</span></div></div><span class="status ${o.status==="Resolvida"?"done":o.status==="Em análise"?"analysis":"pending"}">${o.status}</span></div><p class="small text-secondary mb-0 mt-3">${o.description}</p></div>`;

const allUsers={
 students:[...directory,{name:"Camila Sousa",registration:"2026012410",course:"Ciência da Computação",authorized:false,advisor:"Carlos Mendes",mine:true,hours:0}],
 coordinators:[{name:"Carlos Mendes",registration:"COORD-014",course:"Computação",authorized:true,students:4},{name:"Renata Alves",registration:"COORD-008",course:"Sistemas de Informação",authorized:true,students:2}],
 supervisors:[{name:"Fernanda Oliveira",registration:"SUP-001",course:"Administração do laboratório",authorized:true},{name:"Rafael Santos",registration:"SUP-002",course:"Suporte técnico",authorized:true}]
};
const globalPending=[{id:41,name:"Lucas Lima",registration:"2026012388",role:"Aluno",group:"Engenharia",responsible:"Carlos Mendes"},{id:42,name:"Camila Sousa",registration:"2026012410",role:"Aluno",group:"Computação",responsible:"Carlos Mendes"},{id:43,name:"Paulo Nunes",registration:"COORD-021",role:"Coordenador",group:"Engenharia",responsible:"Supervisão"}];
const extraRequestSeed=[{id:"global-61",name:"Marina Costa",registration:"2025011092",course:"Sistemas de Informação",advisor:"Renata Alves",hours:5,reason:"Finalização do projeto de extensão",date:"Hoje"},{id:"global-62",name:"Pedro Rocha",registration:"2024010433",course:"Engenharia",advisor:"Renata Alves",hours:3,reason:"Reposição de atividade prática",date:"Ontem"}];
const studentExtraRequests=studentStore.get("hour_requests",[]).map((r,i)=>({id:`student-${r.id||i}`,name:"João Silva",registration:"2026012345",course:"Ciência da Computação",advisor:"Carlos Mendes",hours:r.hours,reason:r.reason,date:r.date}));
const coordinatorExtraRequests=coordStore.get("extras",[]).map(r=>({...r,id:`coord-${r.id}`,course:directory.find(x=>x.registration===r.registration)?.course||"Não informado",advisor:"Carlos Mendes"}));
const decidedExtras=supervisorStore.get("extra_decisions",[]);
const initialExtraRequests=[...studentExtraRequests,...coordinatorExtraRequests,...extraRequestSeed].filter((r,i,a)=>a.findIndex(x=>String(x.id)===String(r.id))===i&&!decidedExtras.includes(String(r.id)));
let supState={view:"overview",pending:supervisorStore.get("pending",globalPending),month:new Date(new Date().getFullYear(),new Date().getMonth(),1),selected:new Date(),bookings:supervisorStore.get("bookings",[
 {id:51,date:iso(new Date()),start:"08:00",end:"10:00",title:"Manutenção preventiva",owner:"Supervisora Fernanda",institutional:true,status:"Confirmado"},
 {id:52,date:iso(new Date()),start:"14:00",end:"16:00",title:"Projeto de pesquisa",owner:"João Silva",institutional:false,status:"Confirmado"}
]),limit:supervisorStore.get("limit",25),extras:initialExtraRequests};
const supViews=[["overview","Visão geral","bi-grid"],["agenda","Agenda","bi-calendar3"],["users","Usuários","bi-people"],["approvals","Aprovações","bi-person-check"],["extras","Horas extras","bi-clock-history"],["occurrences","Ocorrências","bi-flag"],["settings","Configurações","bi-sliders"],["profile","Perfil","bi-person"]];
function supNav(){return `<aside class="side student-side"><h5>🛡️ Supervisão</h5>${supViews.map(x=>`<a href="#" class="sup-nav ${supState.view===x[0]?"active":""}" data-view="${x[0]}"><i class="bi ${x[2]}"></i>${x[1]}${x[0]==="approvals"&&supState.pending.length?`<span class="count-pill">${supState.pending.length}</span>`:""}</a>`).join("")}<a href="#/" class="mt-4"><i class="bi bi-arrow-left"></i>Voltar</a></aside>`}
function supMobile(){return `<nav class="mobile-student-nav">${supViews.map(x=>`<button class="sup-nav ${supState.view===x[0]?"active":""}" data-view="${x[0]}">${x[1]}</button>`).join("")}</nav>`}
function supHead(k,t,d,a=""){return `<div class="view-head"><div><span class="eyebrow">${k}</span><h1>${t}</h1><p>${d}</p></div>${a}</div>`}
function supOverview(){const today=supState.bookings.filter(x=>x.date===iso(new Date())).length;return `<section>${supHead("SUPERVISÃO","Visão geral do laboratório","Acompanhe acessos, reservas e situações que precisam de atenção.")}${accessLookupHtml()}${stats([[today,"AGENDAMENTOS HOJE"],[labOccurrences.filter(x=>x.status!=="Resolvida").length,"OCORRÊNCIAS ABERTAS","text-danger"],[supState.pending.length,"APROVAÇÕES PENDENTES"],[supState.extras.length,"PEDIDOS DE HORAS","green"]])}<div class="row g-3 mt-1"><div class="col-lg-7"><div class="panel"><div class="d-flex justify-content-between"><h5>Ocorrências recentes</h5><button class="btn btn-sm btn-light sup-go" data-view="occurrences">Ver todas</button></div>${labOccurrences.slice(0,2).map(occurrenceCard).join("")}</div></div><div class="col-lg-5"><div class="panel"><h5>Resumo de usuários</h5>${[["Alunos",allUsers.students.length,"bi-mortarboard"],["Coordenadores",allUsers.coordinators.length,"bi-person-workspace"],["Supervisores",allUsers.supervisors.length,"bi-shield-check"]].map(x=>`<div class="request-row"><div class="icon-box"><i class="bi ${x[2]}"></i></div><div class="flex-grow-1"><b>${x[0]}</b></div><b>${x[1]}</b></div>`).join("")}<button class="btn btn-outline-dark w-100 mt-3 sup-go" data-view="users">Gerenciar usuários</button></div></div></div></section>`}
function userCard(p,type){return `<div class="user-card" data-search="${(p.name+p.registration+(p.course||"")+(p.advisor||"")).toLowerCase()}"><div class="person-dot">${p.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div><b>${p.name}</b><small class="d-block text-secondary">${p.registration} · ${p.course}</small></div><div class="user-link">${type==="students"?`<small class="text-secondary">Aceito por</small><b class="d-block">${p.advisor}</b>`:`${type==="coordinators"?`<small class="text-secondary">${p.students} alunos vinculados</small>`:"<small class=\"text-secondary\">Acesso administrativo</small>"}`}</div><span class="status ${p.authorized?"done":"denied"}">${p.authorized?"Ativo":"Pendente"}</span></div>`}
function usersView(){return `<section>${supHead("USUÁRIOS","Todos os usuários","Consulte alunos, coordenadores, supervisores e seus vínculos.")}<div class="panel"><div class="access-search mb-3"><input id="globalUserFilter" class="form-control" placeholder="Pesquisar nome, matrícula, curso ou responsável"><button class="btn btn-light"><i class="bi bi-search"></i></button></div><div class="user-tabs">${[["students","Alunos",allUsers.students.length],["coordinators","Coordenadores",allUsers.coordinators.length],["supervisors","Supervisores",allUsers.supervisors.length]].map((x,i)=>`<button class="user-tab ${i?"":"active"}" data-group="${x[0]}">${x[1]} (${x[2]})</button>`).join("")}</div>${Object.entries(allUsers).map(([k,v],i)=>`<div class="user-group ${i?"":"active"}" data-group="${k}">${v.map(x=>userCard(x,k)).join("")}</div>`).join("")}</div></section>`}
function supApprovals(){return `<section>${supHead("APROVAÇÕES","Aprovações globais","Solicitações de todas as turmas, alunos e coordenadores.")}<div class="panel"><h5>${supState.pending.length} solicitações pendentes</h5><div class="mt-3">${supState.pending.length?supState.pending.map(p=>`<div class="approval-card"><div class="d-flex align-items-center gap-3"><div class="person-dot">${p.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div class="flex-grow-1"><b>${p.name}</b><small class="d-block text-secondary">${p.registration} · ${p.role} · ${p.group}</small><small class="text-secondary">Responsável: ${p.responsible}</small></div><div class="approval-actions"><button class="btn btn-success btn-sm sup-decide" data-id="${p.id}" data-action="aprovado">Aprovar</button><button class="btn btn-light btn-sm sup-decide" data-id="${p.id}" data-action="recusado">Recusar</button></div></div></div>`).join(""):`<div class="empty-state">Nenhuma solicitação pendente.</div>`}</div></div></section>`}
function supExtras(){return `<section>${supHead("HORAS EXTRAS","Solicitações de todas as turmas","Analise pedidos de qualquer aluno, independentemente do coordenador responsável.")}<div class="panel"><div class="d-flex gap-2 justify-content-between flex-wrap"><div><h5 class="mb-1">${supState.extras.length} pedidos aguardando análise</h5><small class="text-secondary">A aprovação vale somente para a semana solicitada.</small></div><div class="access-search"><input id="extraSearch" class="form-control" placeholder="Aluno, matrícula, turma ou coordenador"></div></div><div id="supervisorExtras" class="mt-3">${supState.extras.length?supState.extras.map(p=>`<div class="approval-card supervisor-extra" data-search="${(p.name+p.registration+p.course+p.advisor).toLowerCase()}"><div class="d-flex align-items-center gap-3"><div class="icon-box"><i class="bi bi-clock-history"></i></div><div class="flex-grow-1"><div class="d-flex gap-2 align-items-center flex-wrap"><b>${p.name}</b><span class="supervisor-badge">+${p.hours}h</span></div><small class="d-block text-secondary">${p.registration} · ${p.course}</small><small class="d-block text-secondary">Coordenador: ${p.advisor} · ${p.date}</small><p class="small mb-0 mt-2"><b>Justificativa:</b> ${p.reason}</p></div><div class="approval-actions"><button class="btn btn-success btn-sm sup-extra-decision" data-id="${p.id}" data-action="aprovado">Aprovar</button><button class="btn btn-light btn-sm sup-extra-decision" data-id="${p.id}" data-action="recusado">Recusar</button></div></div></div>`).join(""):`<div class="empty-state"><i class="bi bi-check-circle fs-2 d-block mb-2"></i>Nenhum pedido de horas pendente.</div>`}</div></div></section>`}
function supOccurrences(){return `<section>${supHead("OCORRÊNCIAS","Todas as ocorrências","Reportes de alunos, coordenadores e todas as turmas.")}<div class="panel"><div class="d-flex gap-2 justify-content-between flex-wrap"><div class="access-search flex-grow-1"><input id="occurrenceSearch" class="form-control" placeholder="Pesquisar por pessoa, matrícula ou ocorrência"></div><select class="form-select w-auto" id="occurrenceStatus"><option value="all">Todos os status</option><option>Pendente</option><option>Em análise</option><option>Resolvida</option></select></div><div id="allOccurrences" class="mt-3">${labOccurrences.map(occurrenceCard).join("")}</div></div></section>`}
function supCalendar(){const m=supState.month,y=m.getFullYear(),mo=m.getMonth(),start=new Date(y,mo,1-new Date(y,mo,1).getDay());let cells="";for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=iso(d),bs=supState.bookings.filter(b=>b.date===key);cells+=`<button class="cal-day sup-day ${d.getMonth()!==mo?"muted":""} ${key===iso(supState.selected)?"selected":""}" data-date="${key}"><span class="day-num">${d.getDate()}</span><div>${bs.map(b=>`<span class="cal-dot ${b.institutional?"coord-dot":"other"}"></span>`).join("")}</div><small>${bs.length?`${bs.length} reserva${bs.length>1?"s":""}`:""}</small></button>`}return `<div class="calendar-toolbar"><button class="btn btn-light sup-prev"><i class="bi bi-chevron-left"></i></button><h5>${m.toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</h5><button class="btn btn-light sup-next"><i class="bi bi-chevron-right"></i></button></div><div class="calendar-grid">${["DOM","SEG","TER","QUA","QUI","SEX","SÁB"].map(x=>`<span class="weekday">${x}</span>`).join("")}${cells}</div>`}
function supBookingCard(b){return `<div class="booking-card ${b.institutional?"institutional":""}"><div class="d-flex justify-content-between gap-2"><b>${b.title}</b>${b.institutional?`<span class="supervisor-badge">SUPERVISOR</span>`:`<span class="badge-soft">ALUNO</span>`}</div><small class="text-secondary">${b.owner}</small><div class="meta"><span>${brDate(b.date)}</span><span>${b.start}–${b.end}</span></div></div>`}
function supAgenda(){const date=iso(supState.selected),items=supState.bookings.filter(x=>x.date===date);return `<section>${supHead("AGENDA","Agenda do laboratório","Agendamentos da supervisão são identificados em vermelho.",`<button class="btn btn-main" data-bs-toggle="modal" data-bs-target="#supBookingModal"><i class="bi bi-plus-lg"></i> Agendar como supervisor</button>`)}<div class="calendar-wrap"><div class="panel">${supCalendar()}</div><div class="panel"><span class="eyebrow">${brDate(date)}</span><h5 class="mt-2">Agendamentos do dia</h5><div class="mt-3">${items.length?items.map(supBookingCard).join(""):`<div class="empty-state">Nenhuma reserva neste dia.</div>`}</div></div></div>${supBookingModal()}</section>`}
function supBookingModal(){return `<div class="modal fade booking-modal institutional-modal" id="supBookingModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content border-0 rounded-4" id="supBookingForm"><div class="modal-header"><div><span class="eyebrow">SUPERVISÃO</span><h5 class="modal-title">Agendar laboratório</h5><small class="text-secondary">A reserva será identificada como Supervisor</small></div><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="booking-step"><span>1</span><b>Escolha o dia</b></div>${bookingDatePicker("supervisor",iso(supState.selected),supState.bookings)}<div class="booking-step mt-4"><span>2</span><b>Defina o horário</b></div><div class="time-fields"><div class="row g-2"><div class="col-6"><label class="form-label">INÍCIO</label><input class="form-control" name="start" type="time" value="08:00" required></div><div class="col-6"><label class="form-label">TÉRMINO</label><input class="form-control" name="end" type="time" value="10:00" required></div></div></div><div class="booking-step mt-4"><span>3</span><b>Informe a finalidade</b></div><input class="form-control" name="title" placeholder="Ex.: Manutenção preventiva" required><div id="supBookingError" class="text-danger small mt-2"></div></div><div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-main"><i class="bi bi-check-lg"></i> Confirmar reserva</button></div></form></div></div>`}
function settingsView(){return `<section>${supHead("CONFIGURAÇÕES","Regras de utilização","Defina o limite semanal padrão aplicado aos estudantes.")}<div class="row g-3"><div class="col-lg-7"><div class="panel"><h5>Limite semanal</h5><p class="text-secondary">Quantidade máxima de horas que cada aluno pode reservar por semana.</p><div class="d-flex align-items-end gap-2"><span class="config-value" id="supLimitValue">${supState.limit}h</span><span class="text-secondary mb-3">por aluno</span></div><input id="supLimit" class="form-range" type="range" min="5" max="40" step="1" value="${supState.limit}"><div class="d-flex justify-content-between small text-secondary"><span>5h</span><span>40h</span></div><button id="saveLimit" class="btn btn-main mt-4">Salvar configuração</button></div></div><div class="col-lg-5"><div class="panel"><h5>Como funciona</h5><p class="small text-secondary">A alteração será aplicada como limite padrão para todos os alunos. Horas extras aprovadas continuam válidas apenas na semana solicitada.</p><div class="alert alert-warning small mb-0"><i class="bi bi-exclamation-triangle me-1"></i> Reduzir o limite não cancela reservas já confirmadas.</div></div></div></div></section>`}
function supProfile(){const p=supervisorStore.get("profile",{name:"Fernanda Oliveira",email:"fernanda.oliveira@ifma.edu.br",phone:"(98) 99991-4500",sector:"Administração do laboratório"});return `<section>${supHead("PERFIL","Meu perfil","Atualize os dados da sua conta de supervisão.")}<div class="row g-3"><div class="col-lg-5"><div class="panel"><div class="profile-summary"><div class="profile-avatar">FO</div><div><h5 class="mb-1">${p.name}</h5><small class="text-secondary">Supervisora · ${p.sector}</small></div></div><p class="small text-secondary mt-3 mb-0">Acesso administrativo completo ao laboratório.</p></div></div><div class="col-lg-7"><div class="panel"><h5>Dados pessoais</h5><form id="supProfileForm" class="mt-3"><label class="form-label">NOME</label><input class="form-control" name="name" value="${p.name}" required><label class="form-label mt-3">E-MAIL</label><input class="form-control" name="email" type="email" value="${p.email}" required><div class="row g-2 mt-1"><div class="col-md-6"><label class="form-label">SETOR</label><input class="form-control" name="sector" value="${p.sector}" required></div><div class="col-md-6"><label class="form-label">TELEFONE</label><input class="form-control" name="phone" value="${p.phone}"></div></div><button class="btn btn-main mt-3">Salvar alterações</button></form></div><div class="panel mt-3"><h5>Alterar senha</h5><form id="supPasswordForm"><div class="row g-2 mt-3"><div class="col-md-4"><input class="form-control" name="current" type="password" placeholder="Senha atual" required></div><div class="col-md-4"><input class="form-control" name="password" type="password" minlength="6" placeholder="Nova senha" required></div><div class="col-md-4"><input class="form-control" name="confirm" type="password" minlength="6" placeholder="Confirmar" required></div></div><div id="supPasswordError" class="text-danger small mt-2"></div><button class="btn btn-outline-danger mt-3">Atualizar senha</button></form></div></div></div></section>`}

window.supervisorApp=()=>`<div class="shell student-shell supervisor-shell">${supNav()}<div>${supMobile()}<main class="dash">${({overview:supOverview,agenda:supAgenda,users:usersView,approvals:supApprovals,extras:supExtras,occurrences:supOccurrences,settings:settingsView,profile:supProfile}[supState.view]||supOverview)()}</main></div></div>`;
function refreshSupervisor(){A.innerHTML=supervisorApp();bindSupervisor();bindAccessLookup();scrollTo(0,0)}
window.bindSupervisor=()=>{
 bindBookingDatePickers();
 bindBookingAvailability(document.querySelector("#supBookingForm"),supState.bookings);
 document.querySelectorAll(".sup-nav,.sup-go").forEach(x=>x.onclick=e=>{e.preventDefault();supState.view=x.dataset.view;refreshSupervisor()});document.querySelectorAll(".user-tab").forEach(x=>x.onclick=()=>{document.querySelectorAll(".user-tab,.user-group").forEach(y=>y.classList.remove("active"));x.classList.add("active");document.querySelector(`.user-group[data-group="${x.dataset.group}"]`).classList.add("active")});
 const uf=document.querySelector("#globalUserFilter");if(uf)uf.oninput=()=>document.querySelectorAll(".user-card").forEach(x=>x.hidden=!x.dataset.search.includes(uf.value.toLowerCase()));document.querySelectorAll(".sup-decide").forEach(x=>x.onclick=()=>{const p=supState.pending.find(y=>y.id==x.dataset.id);supState.pending=supState.pending.filter(y=>y.id!=x.dataset.id);supervisorStore.set("pending",supState.pending);refreshSupervisor();notify(`${p.name}: cadastro ${x.dataset.action}.`)});
 const ef=document.querySelector("#extraSearch");if(ef)ef.oninput=()=>document.querySelectorAll(".supervisor-extra").forEach(x=>x.hidden=!x.dataset.search.includes(ef.value.toLowerCase()));document.querySelectorAll(".sup-extra-decision").forEach(x=>x.onclick=()=>{const p=supState.extras.find(y=>String(y.id)===x.dataset.id),decisions=supervisorStore.get("extra_decisions",[]);decisions.push(String(p.id));supervisorStore.set("extra_decisions",decisions);supState.extras=supState.extras.filter(y=>String(y.id)!==x.dataset.id);refreshSupervisor();notify(`${p.name}: solicitação de +${p.hours}h ${x.dataset.action}.`)});
 const os=document.querySelector("#occurrenceSearch"),ost=document.querySelector("#occurrenceStatus");const filterOcc=()=>document.querySelectorAll("#allOccurrences .occurrence-card").forEach((x,i)=>{const o=labOccurrences[i],q=(os?.value||"").toLowerCase();x.hidden=(ost.value!=="all"&&o.status!==ost.value)||!(o.title+o.author+o.registration+o.category).toLowerCase().includes(q)});if(os)os.oninput=filterOcc;if(ost)ost.onchange=filterOcc;
 document.querySelector(".sup-prev")?.addEventListener("click",()=>{supState.month=new Date(supState.month.getFullYear(),supState.month.getMonth()-1,1);refreshSupervisor()});document.querySelector(".sup-next")?.addEventListener("click",()=>{supState.month=new Date(supState.month.getFullYear(),supState.month.getMonth()+1,1);refreshSupervisor()});document.querySelectorAll(".sup-day").forEach(x=>x.onclick=()=>{supState.selected=new Date(`${x.dataset.date}T12:00:00`);refreshSupervisor()});
 document.querySelector("#supBookingForm")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target),date=f.get("date"),start=f.get("start"),end=f.get("end"),conflict=supState.bookings.some(b=>b.date===date&&start<b.end&&end>b.start);if(end<=start||conflict){document.querySelector("#supBookingError").textContent=end<=start?"O término deve ser posterior ao início.":"Este horário já está reservado.";return}supState.bookings.push({id:Date.now(),date,start,end,title:f.get("title"),owner:"Supervisora Fernanda",institutional:true,status:"Confirmado"});supervisorStore.set("bookings",supState.bookings);bootstrap.Modal.getInstance(document.querySelector("#supBookingModal"))?.hide();refreshSupervisor();notify("Agendamento da supervisão criado.")});
 const range=document.querySelector("#supLimit");if(range)range.oninput=()=>document.querySelector("#supLimitValue").textContent=range.value+"h";document.querySelector("#saveLimit")?.addEventListener("click",()=>{supState.limit=Number(range.value);supervisorStore.set("limit",supState.limit);notify("Limite semanal atualizado.")});
 document.querySelector("#supProfileForm")?.addEventListener("submit",e=>{e.preventDefault();supervisorStore.set("profile",Object.fromEntries(new FormData(e.target).entries()));refreshSupervisor();notify("Perfil atualizado.")});document.querySelector("#supPasswordForm")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target);if(f.get("password")!==f.get("confirm")){document.querySelector("#supPasswordError").textContent="As senhas não coincidem.";return}e.target.reset();notify("Senha atualizada.")});
};
if(["#/admin","#/coordenador","#/estudante"].includes(location.hash))render();
